# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
default: &default
  database_password: rhynofox
  emailusername: amyjemail
  emailpassword: ..rhyn0faux..
  facebook_api_key: "233579603878949"
  facebook_api_secret: ff1fea8aac61eef9aa349d46a85c26ec
  aws_access_key_id: AKIAJCADHYMW7UHMOILA
  aws_secret_access_key: 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 
  aws_region: us-west-2
  aws_bucket: bara-farmstay

test:
  <<: *default
  test_secret_key_base: 0639f41ac1bae049227c79084368fcfc5c378acb0822dbc5df28541697718de96f4afd13271ed32e8021dbc39d1a669a8247b1f2dbe5b25d1b8a8136ae906439

development:
  <<: *default
  development_secret_key_base: f34a7bb405c21e1ed849a2a4b903b78ec94f18dd27a0b7d496316f09ed05e95d6909a485099428960731213513acd4782cfd9d8cdae4539b58b0dc6b1b4e83a5

staging:
  <<: *default
  staging_username: ajording
  staging_password: rhyn0fox
  secret_key_base: 94d18f3abed275c356cf3a766516254c14eda67265a7bcde1e16c0e989f497ab1ef1ed231dbb572ffeb88420e6a17159194aba3b53e6bf4fedaf484dec80a398
  devise_secret_key: ad4f7c1f59f3d86b49a9adcbfc688deb03e65d793fbada1d987247199c341ebc54902ef45bd4f5646abe7e9ed150c00d7198bcc99d0ca85030037c07609b2aa8

production:
  <<: *default
  secret_key_base: 94d18f3abed275c356cf3a766516254c14eda67265a7bcde1e16c0e989f497ab1ef1ed231dbb572ffeb88420e6a17159194aba3b53e6bf4fedaf484dec80a398
  devise_secret_key: ad4f7c1f59f3d86b49a9adcbfc688deb03e65d793fbada1d987247199c341ebc54902ef45bd4f5646abe7e9ed150c00d7198bcc99d0ca85030037c07609b2aa8

#development:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

#test:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

#staging:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>